# Generated by Django 4.2.23 on 2025-07-08 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_editor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editor',
            name='title',
        ),
    ]
